In [33]:
import tensorflow as tf
from tensorflow.keras.layers import Input, Reshape, Conv2D, BatchNormalization, Softmax, Conv1D, MaxPool1D, AvgPool1D

In [14]:
a = tf.constant([1,2,3,4,5,6,7,8,9,10])

In [27]:
output_tensor = tf.map_fn(lambda i: a[i:i+4], elems=tf.range(start=0, limit=8, delta=2))


In [25]:
output_tensor

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[ 1,  2,  3,  4],
       [ 3,  4,  5,  6],
       [ 5,  6,  7,  8],
       [ 7,  8,  9, 10]])>

In [30]:
a = tf.reshape(a, [1,10,1])

In [ ]:
tf.reduce_m

In [37]:
AvgPool1D(5, strides = 1, padding='same')(a)

<tf.Tensor: shape=(1, 10, 1), dtype=float32, numpy=
array([[[2. ],
        [2.5],
        [3. ],
        [4. ],
        [5. ],
        [6. ],
        [7. ],
        [8. ],
        [8.5],
        [9. ]]], dtype=float32)>

In [35]:
a = tf.cast(a, tf.float32)

In [7]:
initializer = tf.keras.initializers.Ones()

In [9]:
conv = Conv1D(3, kernel_size=5, strides=2,kernel_initializer=initializer, padding='valid', activation=None)

In [13]:
conv(a)

<tf.Tensor: shape=(1, 3, 3), dtype=float32, numpy=
array([[[15., 15., 15.],
        [25., 25., 25.],
        [35., 35., 35.]]], dtype=float32)>